server:
  port: "8081"

database:
  host: "localhost"
  port: 3307
  username: "root"
  password: "123456"
  database: "wallet_db"

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0

scanner:
  scan_interval: 30
  max_blocks_per_scan: 100
  retry_attempts: 3

ethereum:
  testnet:
    rpc_url: "https://sepolia.infura.io/v3/YOUR_PROJECT_ID"
    chain_id: 11155111
    confirmations: 12
  mainnet:
    rpc_url: "https://mainnet.infura.io/v3/YOUR_PROJECT_ID"
    chain_id: 1
    confirmations: 12

bsc:
  rpc_url: "https://bsc-dataseed1.binance.org/"
  chain_id: 56
  confirmations: 15

wallet:
  hd_wallet:
    mnemonic: ""
    derivation_path: "m/44'/60'/0'/0"
  hot_wallet:
    max_balance: "1.0"
    collection_threshold: "0.1"
  cold_wallet:
    address: ""

jwt:
  secret: "your-secret-key"
  expiration_hours: 24 